### ISSUE TITLE
Migrate codebase to black and isort

### ISSUE THREAD

**Issue by florianfischer91** [potassco/clorm#117]
I was wondering if @daveraja you would be open to use black and isort to mange the project's style?
I could also integrate it into CI.

**Comment by daveraja** [comment]
Yes. I'm fine to switch to black and isort for the project. There are a few very minor things about black's formatting that annoy me but I can learn to live with it :). And I would agree that it is better to stick to a best-practice type formatting style (rather than what was intuitive to me when clorm was started).

**Comment by florianfischer91** [comment]
Cool, nice to hear :-)
There are three options in black which can be configured:
- line-length (default 88)
- skip normalizing string quotes or prefixes
- don't use trailing commas as a reason to split lines

Do you have any preferences?

**Comment by daveraja** [comment]
In general I'm fine to go with whatever you prefer (or the default). The only one I feel a bit strongly about is that the line length doesn't go above 100; so either 88 or 98 would be ok with me.
