### ISSUE TITLE
Clarify non-conda installation Python bindings

### ISSUE THREAD

**Issue by felixyz** [potassco/clorm#22]
I prefer to not use Anaconda. The installation instructions mention how to [install from source](https://clorm.readthedocs.io/en/stable/clorm/installation.html), but there is no mention of how to get the Python bindings set up. I have installed clasp and gringo through apt, but when I try to run the example:

```
> python quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from clorm import monkey; monkey.patch() # must call this before importing clingo
  File "/home/felixyz/.local/share/virtualenvs/clorm-bmqSdbdr/lib/python3.7/site-packages/Clorm-1.0.1-py3.7.egg/clorm/__init__.py", line 1, in <module>
  File "/home/felixyz/.local/share/virtualenvs/clorm-bmqSdbdr/lib/python3.7/site-packages/Clorm-1.0.1-py3.7.egg/clorm/orm.py", line 17, in <module>
ModuleNotFoundError: No module named 'clingo'
```

(Running Python 3.7.5 under pipenv)

I then looked at the [Potassco installation instructions](https://potassco.org/doc/start/) but they only point to the [release page](https://github.com/potassco/clingo/releases/) which states that the " easiest way to obtain Python enabled clingo packages is using Anaconda", but it doesn't explain if there is some other (less easy) way to get Python enabled clingo.

Since the non-conda installation is mentioned as an option by the docs, it would be very helpful if there was instructions to get the "original" Python wrapper working as well.

One more thing: I was very happy to discover that this project is alive and well (I first had a look at it a few months ago) and that it has found a place under the official Potassco umbrella. Great! I think this project can make it a lot easier to introduce ASP to teams with no prior knowledge of LP. I'm attempting to do so right now :)

**Comment by daveraja** [comment]
The Clorm installation from source instructions does assume that Clingo 
and the Clingo Python module have already been installed. I'll modify 
the docs to clarify this.

Unfortunately, from what I can see, the clasp/gringo packages on the 
Ubuntu apt repository do not contain the Clingo Python module. It's a 
bit confusing because Python support has been compiled into the clingo 
binary itself (for example, when I run "clingo --version" it says "with 
Python 3.7.1"), but there is no Python module in the list of installed 
files.  Hence when the Clorm code executes "import clingo" it raises 
ModuleNotFoundError.

So from what I can tell it's a problem with the apt gringo package. 
There may be a reasonable explanation for this but you'll have to ask on 
the main Potassco mailing list.

Unfortunately, I think this means that you are going to have to compile 
Clingo from source. The instructions are here: 
https://github.com/potassco/clingo/blob/master/INSTALL.md

If you are familiar with using Cmake then its not too difficult, but it 
could still be a hassle if you need to package it up to distribute 
amongst a team. The Cmake variables that are relevant to Python are 
here: 
https://github.com/potassco/clingo/blob/master/INSTALL.md#python-support

Sorry I can't offer a better option.

Regarding Clorm itself. Yes, I'm very glad that the Potsdam group were 
happy to adopt Clorm under the official Potassco umbrella. My hope is 
that it will make ASP more accessible for integrating into Python 
applications, so I'll be interested to hear your experience introducing 
it to a non LP team, and of course happy to answer any questions.

**Comment by daveraja** [comment]
I've added a note in the documentation with a pointer to the Clingo instructions for building from source. Also added a comment that the Ubuntu apt packages may not work because of the missing python module.

**Comment by felixyz** [comment]
@daveraja Thanks for your very helpful answer! I opened an issue on the clingo repo instead.
