### ISSUE TITLE
Querying: Consider replacing and_, or_, and not_ with magic methods

### ISSUE THREAD

**Issue by 0x326** [potassco/clorm#28]
The following operators could be used to replace the `and_`, `or_`, and `not_` query functions:
- `&` via `__and__(...)`
- `|` via `__or__(...)`
- `-` via `__neg__(...)`

## Current syntax

```python
# Find the Person with id "dave" or with address "UNSW"
query1=fb.select(Person).where(or_(Person.id == "dave", Person.address == "UNSW"))
```

## Proposed syntax

```python
# Find the Person with id "dave" or with address "UNSW"
query1=fb.select(Person).where((Person.id == "dave") | (Person.address == "UNSW"))
```

**Comment by 0x326** [comment]
<https://docs.python.org/3/reference/datamodel.html#object.__and__>

**Comment by daveraja** [comment]
At some point I briefly thought about this but resisted trying it because it means treating the bitwise operators as specialised query logical operators; since Python doesn't let you overload the actual logical operators.

But I do agree that it provides a more intuitive syntax, and using ``and_()``, ``or_()``, and ``neg_()`` functions is a bit ugly.

Just looking at what some Python ORMs have done. SQLAlchemy uses the ``and_()``, etc, functions. On the other hand Peewee (which is what I've mostly used for inspiration) does overload bitwise operators.

So overall, I think the nicer syntax is a good idea and I'll try to implement this. But I think instead of overloading ``__neg__()`` it's better to overload  ``__invert__()`` which is the tilda operator ``~``. This makes it consistent with Peewee, and SQLAlchemy also uses it.

**Comment by daveraja** [comment]
I added the overloaded ``&``,``|``,``~`` operators to the query syntax:

```python
# Find the Person with id "dave" or with address that is not "UNSW"
query1=fb.select(Person).where((Person.id == "dave") | ~(Person.address == "UNSW"))
```

It is now part of v1.0.4 which I've just uploaded to anaconda.
