### ISSUE TITLE
Add typing

### ISSUE THREAD

**Issue by florianfischer91** [potassco/clorm#62]
I would ask if is possible to add typing to at least the 'public'-Attributes (including methods)? In this way if you use an IDE like PyCharm or VS-Code you would get completion suggestions and also information about the 'allowed' type of an argument immediately instead of reading the doc-string.
Take the `add_facts`-Method for example
```
def add_facts(self, facts):
    '''Add facts to the control object. Note: facts must be added before grounding.

       This function can take an arbitrary collection containing a mixture
       of ``clorm.Predicate`` and ``clingo.Symbol`` objects. A
       ``clorm.FactBase`` is also a valid collection but it can only contain
       ``clorm.Predicate`` instances.

    Args:
      facts: a collection of ``clorm.Predicate`` or ``clingo.Symbol`` objects

    '''
    control_add_facts(self._wrapped, facts)
```
So instead of describing the allowed types for `facts` i would propose to add the type-information like
```
def add_facts(self, facts: Sequence[Union[Predicate, oclingo.Symbol]]):
    '''Add facts to the control object. Note: facts must be added before grounding.

    Args
    ----------
    facts: a sequence of facts

    '''
    control_add_facts(self._wrapped, facts)
```

What do you think?

**Comment by daveraja** [comment]
Yes. I think this sounds reasonable and would make clorm more usable for a wider audience.  It might also be a good opportunity to clean up a few API calls that over-use variable positional arguments. 

I think there will be some API calls where the return type hint may not be very useful. In particular, `Query.all()` would have to have as a return type hint a generator over `Any`; since the value that is iterated over depends on how the query is constructed. 

However, overall I agree that adding type hints is a good idea.

**Comment by florianfischer91** [comment]
Glad to hear, that you like the idea :-)

Yeah, I agree with you that inferring the correct return type of a query is probably not so easy especially if you select multiple predicates, joining them etc... Perhaps it's possible when selecting just a single predicate.

If you want some help with the typing-stuff just let me know
